replicaCount: 1

image:
  repository: lrehdocker/time-service
  pullPolicy: IfNotPresent
  tag: e1f36c839e953683c9fddd36198dc9980cbe7844

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}
