replicaCount: 1

image:
  repository: lrehdocker/time-service
  pullPolicy: IfNotPresent
  tag: 1bad3ec43e2de22f8f566e680f5609935e607b2b

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}
