replicaCount: 1

image:
  repository: lrehdocker/time-service
  pullPolicy: IfNotPresent
  tag: d53838db11213b4ffe2b4a6dee008f0be473ddd0

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}
